### PR TITLE
Added Compressible Assets + Vary Support

### PR DESCRIPTION
**Pull request by cseufert**
Middleware not looks at Content-Type to determine if its worth compressing the response, and also adds a Vary: Content-Encoding if its not already present.

### CODE REVIEW

**Comment by cseufert** [comment]
This should close #1

**Comment by oscarotero** [comment]
Thanks for your contribution and sorry for the delay of my response.
This pull request contain multiple changes, some of them I am not convinced.

- Compress only some Content-Types: Yes, it's a good idea, but I'd use the same syntax that other middlewares with similar option. For example [payload](https://github.com/middlewares/payload#contenttype). And it's not neccesary return a clone using the `with*` syntax.
```php
(new Middlewares\GzipEncoder())->contentType([
    'application/json',
    'text/html'
]),
```
- Add Content-Length header: Because the body can be changed in multiple middlewares, it's better to remove this header, to avoid other middleware to change the content but keep the same content-length header. There's a middleware to add it, that should be placed just before emitting, when we have the final content: https://github.com/middlewares/content-length
- Add Vary header: This is out of the scope of this middleware. Like Content-Length, the Vary header should be added in a different middleware.

If you want to do these changes (keep only the contentType functionality), I'll be happy to merge it.
Thanks!

**Comment by cseufert** [comment]
I agree with you about the content-length header.

I am not so sure about the Vary header though, how does another middleware know that the output encoding was changed based on reading the Accept header? Seems awkward to pass that information to another middleware, and have an interdependency to use this middleware

**Comment by cseufert** [comment]
I have updated the configuration to allow either regex or list of content-types

**Comment by oscarotero** [comment]
Ok, thanks again for the changes. I have two suggestions:

- `Vary` header should be optional and enabled with `$encoder->vary()`.
- I don't like to have two methods for the same thing and mutually exclusive. I'm more inclined in something like this:

```php
$encoder->contentType(
    'application/json',
    'text/*'
),
```

So, if a content type has a `*`, it could be converted as a regexp in this way:

```php
if (strpos($type, '*') !== false) {
    $regexp = '#^'.str_replace('*', '.*').'$#'; // #^text/.*$#
    preg_match($regexp, $contentType);
}
```

**Comment by cseufert** [comment]
I have refactored this to a single contentType function, and it now checks the first character, if its a slash it treats the string as a regex, else it does a string comparison.

I think it's a bad idea to have the Vary header as opt-in, and it really does not make sense to have it opt-out either.

**Comment by oscarotero** [comment]
Ok, thanks for your contribution!

**Pull request merged**
